name: ✨ Feature Request
description: Suggest a new feature or enhancement for the website
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Alternative approaches could be...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - UI/UX Improvement
        - New Page/Section
        - Navigation Enhancement
        - Performance Optimization
        - Accessibility
        - Mobile Experience
        - Content Management
        - SEO/Analytics
        - Other
    validations:
      required: true

  - type: textarea
    id: mockup
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples from other sites
      placeholder: Drag and drop images or provide links to examples

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Opinion)
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be useful
        - High - Very important
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request
      placeholder: Any other details...

  - type: checkboxes
    id: checks
    attributes:
      label: Before submitting
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: This feature aligns with the website's purpose and goals
          required: true
